#!/bin/bash

### BEGIN INIT INFO
# Provides:          scaffolding
# Required-Start:    $syslog $network $named $time $local_fs
# Required-Stop:     $syslog $network $named $time $local_fs
# Default-Start:     5
# Default-Stop:      6
# Short-Description: scaffolding server for nodejs applications
# Description:       It is what it says one line above
### END INIT INFO

DIR=/home/pi/programs/nodejs/Scaffolding
DAEMON=server.coffee
DAEMON_NAME=scaffolding
PIDFILE=/var/run/$DAEMON_NAME.pid
LOGFILE=/var/log/$DAEMON_NAME.log

init() {
	rm $DIR/error.log 2> /dev/null
}

checkExecution() {
	if [ $? -eq 0 ]; then
		printf 'OK\n'
	else
		printf 'FAIL\n'
	fi
}

do_start() {
	printf "Starting %s service ...\n" $DAEMON_NAME
	printf "... Changing work directory ... "
	cd $DIR 2>> $DIR/error.log
	checkExecution

	printf "... Starting server ... "
	./$DAEMON > $LOGFILE &
	checkExecution

	printf "... Server started with PID: "
	printf $! > $PIDFILE
	printf "%d\n" $!
}

do_stop() {
	printf "Stopping %s service ...\n" $DAEMON_NAME
	APP_PID=$(<$PIDFILE)
	printf "... killing process with PID: %d ... " $APP_PID
	kill $APP_PID 2>> $DIR/error.log
	checkExecution
}

get_status() {
	APP_PID=$(<$PIDFILE)
	local PS=`ps cax | grep $APP_PID`
	echo "$PS"
}

init
case $1 in
	start)
		do_start
		;;
	stop)
		do_stop
		;;
	status)
		PS=$(get_status)
		if [ -z "$PS" ]; then
			printf "Service $DAEMON_NAME is not running.\n"
		else
			printf "Service $DAEMON_NAME is running.\n"
		fi
		;;
	restart)
		do_stop
		do_start
		;;
	install)
		PS=$(get_status)
		if [ -n "$PS" ]; then
			printf "Service $DAEMON_NAME is running, stopping server.\n"
			do_stop
		fi
		printf "installing $DAEMON_NAME service ... \n"
		printf "... creating symlink ... "
		ln -s $DIR/$DAEMON_NAME /etc/init.d/$DAEMON_NAME 2>> $DIR/error.log
		checkExecution

		printf "... updating rc ... "
		update-rc.d $DAEMON_NAME defaults 2>> $DIR/error.log
		checkExecution
		;;
	uninstall|remove)
		PS=$(get_status)
		if [ -n "$PS" ]; then
			printf "Service $DAEMON_NAME is running, stopping server."
			do_stop
		fi
		printf "removing $DAEMON_NAME service ... \n"
		printf "... removing rc ... "
		update-rc.d $DAEMON_NAME remove 2>> $DIR/error.log
		checkExecution

		printf "... removing symlink ... "
		rm /etc/init.d/$DAEMON_NAME 2>> $DIR/error.log
		checkExecution
		;;
	*)
		printf 'Usage: service scaffolding start|stop|restart|status|install|remove|uninstall\n'
		printf 'install/remove requires admin rights\n'
		;;
esac

if [ -s "error.log" ]; then
	printf "Execution finished with errors:\n"
	cat error.log
else
	printf "Execution finished successfully\n"
fi

exit 0
